=== Stones2Stars/Stones2Stars/Assets/XML/Schema/Civ4GameText.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.firaxis.com" elementFormDefault="qualified" targetNamespace="http://www.firaxis.com">
  <xs:element name="Civ4GameText">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TEXT" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element ref="Tag"/>
              <xs:element name="English" type="Gametext"/>
              <xs:element name="French" type="Gametext" minOccurs="0"/>
              <xs:element name="German" type="Gametext" minOccurs="0"/>
              <xs:element name="Italian" type="Gametext" minOccurs="0"/>
              <xs:element name="Spanish" type="Gametext" minOccurs="0"/>
              <xs:element name="Polish" type="Gametext" minOccurs="0"/>
              <xs:element name="Russian" type="Gametext" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tag">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="TXT_[\c-[:]]*|AI_DIPLO_[\c-[:]]*|USER_DIPLO_[\c-[:]]*|INTERFACE_[\c-[:]]*"/>
        <xs:whiteSpace value="collapse"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType mixed="true" name="Gametext">
    <xs:all>
      <xs:element name="Text" type="xs:string" minOccurs="0"/>
      <xs:element name="Gender" type="xs:NMTOKEN" minOccurs="0"/>
      <xs:element name="Plural" type="xs:NMTOKEN" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Map_Categories_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_AQUATIC</Tag>
		<English>Aquatic Plot</English>
		<German>Wasserfeld</German>
		<French>Case aquatique</French>
		<Italian>Casella acquatica</Italian>
		<Russian>Море</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_CISLUNAR</Tag>
		<English>Cislunar Plot</English>
		<French>Case Cislunaire</French>
		<Italian>Casella cislunare</Italian>
		<German>Weltraumfeld</German>
		<Russian>Орбита Луны</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_DISTANT</Tag>
		<English>Distant Plot</English>
		<French>Case Distante</French>
		<Italian>Casella di spazio distante</Italian>
		<Russian>Дальний сектор</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_EARTH</Tag>
		<English>Earth Plot</English>
		<German>Erdfeld</German>
		<French>Case terrienne</French>
		<Italian>Casella terrestre</Italian>
		<Russian>Планета Земля</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_GALACTIC</Tag>
		<English>Galactic Plot</English>
		<German>Galaxiefeld</German>
		<Italian>Casella galattica</Italian>
		<French>Case galactique</French>
		<Russian>Сектор галактики</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_HYPERSPACE</Tag>
		<English>Hyperspace Plot</English>
		<French>Case d'Hyperspace</French>
		<Italian>Casella d'iperspazio</Italian>
		<Russian>Гиперпространство</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_INTERSTELLAR</Tag>
		<English>Interstellar Plot</English>
		<French>Case Interstellaire</French>
		<Italian>Casella interstellare</Italian>
		<Russian>Межзвездное пространство</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_JOVIAN</Tag>
		<English>Jovian Plot</English>
		<German>Jupiterfeld</German>
		<French>Case jovienne</French>
		<Italian>Casella gioviana</Italian>
		<Russian>Атмосфера Юпитера</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_LUNAR</Tag>
		<English>Lunar Plot</English>
		<German>Mondfeld</German>
		<Italian>Casella lunare</Italian>
		<French>Case lunaire</French>
		<Russian>Поверхность Луны</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_MARTIAN</Tag>
		<English>Martian Plot</English>
		<German>Marsfeld</German>
		<Italian>Casella marziana</Italian>
		<French>Case martienne</French>
		<Russian>Поверхность Марса</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_MILKY_WAY</Tag>
		<English>Milky Way Plot</English>
		<Italian>Casella della via lattea</Italian>
		<French>Case de Voie lactée</French>
		<Russian>Млечный Путь</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_PLASMA</Tag>
		<English>Plasma Plot</English>
		<Italian>Casella di plasma</Italian>
		<German>Plasmafeld</German>
		<French>Case de plasma</French>
		<Russian>Плазма</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_SOLAR_SYSTEM</Tag>
		<English>Solar System Plot</English>
		<German>Sonnensystemfeld</German>
		<French>Case du système solaire</French>
		<Italian>Casella del sistema solare</Italian>
		<Russian>Солнечная система</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_SUBTERRANEAN</Tag>
		<English>Subterranean Plot</English>
		<German>unterirdisches Feld</German>
		<French>Case souterraine</French>
		<Italian>Casella sotterranea</Italian>
		<Russian>Недра Земли</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_TITANIC</Tag>
		<English>Titanic Plot</English>
		<French>Case de Titan</French>
		<Italian>Casella di Titano</Italian>
		<Russian>Поверхность Титана</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_UNIVERSAL</Tag>
		<English>Universal Plot</English>
		<French>Case Universelle</French>
		<Italian>Casella universale</Italian>
		<Russian>Вселенная</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MAPCATEGORY_VENUSIAN</Tag>
		<English>Venusian Plot</English>
		<German>Venusfeld</German>
		<Italian>Casella venusiana</Italian>
		<French>Case vénusienne</French>
		<Russian>Поверхность Венеры</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/Modules/zWIP/Extinction/Extinction_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BONUS_MAMMOTH_GRAVEYARD</Tag>
		<English>Mammoth Graveyard</English>
		<Italian>Cimitero dei mammut</Italian>
		<Russian>Êëàäáèùå ìàìîíòîâ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_MAMMOTH_GRAVEYARD_PEDIA</Tag>
		<English>When mammoths go extinct in the wild their map bonus is replaced by a graveyard. This may be their bones, or fossils or frozen mammoths.</English>
		<Russian>Когда мамонты вымирают в дикой природе, их бонусные ресурсы на карте заменяется кладбищами. Это могут быть их кости, или окаменелости, или замороженные туши мамонтов.</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/TechHelpText.xml
<?xml version="1.0" encoding="utf-8"?>

<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_HERITAGE_FOLKLORE_DART_FROG</Tag>
		<English>Folklore - Dart Frog</English>
		<French>Mythe de la Grenouille venimeuse</French>
		<German>Mythos des Baumsteigerfroschs</German>
		<Italian>Mito della rana velenosa</Italian>
		<Russian>Миф о древолазе</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Captives_Concept_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_CONCEPT_WORLD_VIEW</Tag>
		<English>1. World View</English>
		<French>1. Vision du Monde</French>
		<Italian>Visione del mondo</Italian>
		<German>1. Weltanschauung</German>
		<Polish>1. Swiatopogl&#185;d</Polish>
		<Russian>1. Мировоззрения</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_CONCEPT_WORLD_VIEW_PEDIA</Tag>
		<English>The World Views are like Civics, but they only have two states, on and off. They are an experiment and are implemented as buildings rather than Civics due to the number we are thinking of having. The current World Views are:[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Cannibalism[\BOLD] - allows the butchering of Captives like animals.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Human Sacrifice[\BOLD] - allows the sacrifice of Captives.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Slavery[\BOLD] - allows selling or settling Captives as Slaves.</English>
		<French>Les Visions du monde sont comme les doctrines, mais en étant soit activés ou non. Il s'agit d'un essai expérimental, et sont implémentées en tant que batiment. Les visions du monde actuelles sont:[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Cannibalisme[\BOLD] - Permet de manger les prisonniers comme des animaux.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Sacrifice Humain[\BOLD] - Permet le sacrifice des prisonniers.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Esclavage[permet la vente des prisonnier comme esclaves.</French>
		<Italian>Le visioni del mondo sono come le forme di governo e quindi possono essere attive o no. Sono ancora in fase sperimentale e sono state introdotte come edifici dato che sono poche in confronto alle forme di governo. Le attuali visioni del mondo sono:[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Cannibalismo[\BOLD] - permette di uccidere e macellare i prigionieri come gli animali.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Sacrifici umani[\BOLD] - permette di sacrificare i prigionieri.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Schiavismo[\BOLD] - permette di vendere o utilizzare i prigionieri come schiavi.</Italian>
		<German>Weltanschauung sind wie Gesellschaftsformen, außer das es nur zwei Zustände gibt, aktiv und inaktiv. Diese sind ein Experiment und eher als Gebäude umgesetzt statt als Gesellschaftsformen aufgrund der Anzahl welche wir erwarten. Aktuelle Weltanschauungen sind:[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Kannibalismus[\BOLD] - Erlaubt das Schlachten von Gefangenen wie Tiere.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Menschenopfer[\BOLD] - Erlaubt das Opfern von Gefangenen.[NEWLINE][NEWLINE][ICON_BULLET][BOLD]Sklaverei[\BOLD] - Erlaubt das Verkaufen oder Ansiedeln von Gefangenen als Sklaven.</German>
		<Polish>Swiatopogl&#185;d jest podobny do ustroju. Obecnie istniej&#185; 3 &#156;wiatopogl&#185;dy w grze: Kanibalizm, Ofiary z ludzi oraz Niewolnictwo.</Polish>
		<Russian>Мировоззрения в чем-то похожи на Парадигмы, но в них только два состояния - принятие или запрет. Они являются экспериментом и реализованы в виде зданий, а не Парадигм, из-за количественных ограничений. Ниже приведены текущие мировоззрения:[NEWLINE][NEWLINE][TAB][ICON_BULLET][BOLD]Каннибализм[\BOLD] - позволяет убивать пленных как животных.[NEWLINE][NEWLINE][TAB][ICON_BULLET][BOLD]Человеческие жертвоприношения[\BOLD] - позволяет приносить пленников в жертву богам и духам в обмен на прирост культуры и счастливые лица.[NEWLINE][NEWLINE][TAB][ICON_BULLET][BOLD]Рабовладение[\BOLD] - позволяет захватывать, продавать или заселять пленных как рабов.</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Human_Sacrifice_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_WORLDVIEW_HUMAN_SACRIFICE_ACTIVE</Tag>
		<English>Worldview - Human Sacrifice active</English>
		<French>
			<Text>Vision du Monde - Sacrifice Humain actif</Text>
			<Gender>Female</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Sacrifici umani attivi (concezione del mondo)</Italian>
		<Polish>Swiatopogl&#185;d - Ofiary z ludzi aktywne</Polish>
		<Russian>Æåðòâû</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ALTAR_FOR_HUMAN_SACRIFICE</Tag>
		<English>Altar for Human Sacrifice</English>
		<French>
			<Text>Autel pour sacrifice humain</Text>
			<Gender>Male</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Altare per sacrifici umani</Italian>
		<Polish>O&#179;tarz Ofiar z ludzi</Polish>
		<Russian>Æåðòâåííûé àëòàðü</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_ALTAR_FOR_HUMAN_SACRIFICE_PEDIA</Tag>
		<English>Altar for Human Sacrifice</English>
		<French>Autel pour Sacrifice Humain</French>
		<Italian>Un altare utilizzato per i sacrifici umani</Italian>
		<Polish>O&#179;tarz Ofiar z ludzi</Polish>
		<Russian>Àëòàðü äëÿ ÷åëîâå÷åñêèõ æåðòâîïðèíîøåíèé</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_WORLDVIEW_HUMAN_SACRIFICE</Tag>
		<English>Worldview - Human Sacrifice</English>
		<French>
			<Text>Vision du Monde - Sacrifice Humain</Text>
			<Gender>Female</Gender>
			<Plural>0</Plural>
		</French>
		<Italian>Sacrifici umani (concezione del mondo)</Italian>
		<Polish>Swiatopogl&#185;d - Ofiary z ludzi</Polish>
		<Russian>Æåðòâîïðèíîøåíèÿ</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_WORLDVIEW_HUMAN_SACRIFICE_HELP</Tag>
		<English>Allows you to sacrifice human and Neanderthal captives for culture or happiness.</English>
		<French>Vous permet de sacrifier les hommes et néanderthaliens pour de la culture ou du bonheur.</French>
		<Italian>Ti permette di sacrificare i prigionieri umani e Neanderthal per ottenere cultura o felicità.</Italian>
		<Polish>Pozwala na sk&#179;adanie ofiar z pojmanych je&#241;c&#243;w.</Polish>
		<Russian>Ïîçâîëÿåò ïðèíîñèòü â æåðòâó ÷åëîâå÷åñêèõ è íåàíäåðòàëüñêèõ ïëåííèêîâ äëÿ óâåëè÷åíèÿ êóëüòóðû èëè íàñòðîåíèÿ ãðàæäàí.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_WORLDVIEW_HUMAN_SACRIFICE_PEDIA</Tag>
		<English>Human Sacrifice...</English>
		<French>Sacrifice Humain...</French>
		<Italian>I sacrifici umani furono praticati a lungo nella preistoria.</Italian>
		<Polish>Ofiary z ludzi...</Polish>
		<Russian>×åëîâå÷åñêèå æåðòâîïðèíîøåíèÿ....</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_REMOVE_WV_HUMAN_SACRIFICE</Tag>
		<English>Stop Human Sacrifice in your nation.</English>
		<French>Arrêter les Sacrifices Humains au sein de votre nation.</French>
		<Italian>Ferma i sacrifici umani nella tua nazione.</Italian>
		<Polish>Ofiary z ludzi w Twoim imperium zostaj&#185; zakazane.</Polish>
		<Russian>Ïðåêðàòèòü ÷åëîâå÷åñêèå æåðòâîïðèíîøåíèÿ â âàøåé ñòðàíå.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_SACRIFICE_CAPTIVE</Tag>
		<English>Sacrifice a captive for Culture, Happiness.</English>
		<French>Sacrifiez un captif pour la Culture et le Bonheur.</French>
		<Italian>Sacrifica prigioniero per cultura e felicità.</Italian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_SACRIFICE_CAPTIVE_HELP</Tag>
		<English>Increases the culture and happiness of the city. Unit is consumed.</English>
		<French>Augmente la culture et le bonheur de la ville. L'unité est consommée.</French>
		<Italian>[NEWLINE]Aumenta la cultura e la felicità della città. L'unità è consumata nel processo.</Italian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MSG_NO_HUMAN_SACRIFICE</Tag>
		<English>Your nation has banned human sacrifice.</English>
		<French>Votre nation a banni le sacrifice humain.</French>
		<Italian>La tua nazione ha vietato i sacrifici umani.</Italian>
		<Polish>Tw&#243;j nar&#243;d przesta&#179; zakaza&#179; ofiar z ludzi.</Polish>
		<Russian>Â âàøåé ñòðàíå çàïðåùåíû æåðòâîïðèíîøåíèÿ.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_REMOVE_WV_HUMAN_SACRIFICE</Tag>
		<English>End the practice of Human Sacrifice.</English>
		<French>Arrête les pratiques du sacrifice humain.</French>
		<Italian>Ferma la pratica dei sacrifici umani.</Italian>
		<Polish>Koniec prakty sk&#179;adania ofiar z ludzi.</Polish>
		<Russian>Ïðåêðàòèòü ïðàêòèêó ÷åëîâå÷åñêèõ æåðòâîïðèíîøåíèé.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_REMOVE_WV_HUMAN_SACRIFICE_MESSAGE</Tag>
		<English>Your people no longer practice human sacrifice.</English>
		<French>Votre peuple ne pratique plus de sacrifices humains.</French>
		<Italian>La tua gente non pratica più i sacrifici umani.</Italian>
		<Polish>Twoi ludzie przestali sk&#179;ada&#230; ofiary z ludzi.</Polish>
		<Russian>Âàø íàðîä áîëåå íå ïðàêòèêóåò ÷åëîâå÷åñêèå æåðòâîïðèíîøåíèÿ.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_SACRIFICE_CAPTIVE</Tag>
		<English>The best results come with the best altars (Altar for Human Sacrifice or the better Sacrificial Alter). Better results occur with the Druid and MesoAmerican religions and their monastery and cathedrals. Some wonders also improve the outcome.</English>
		<French>Les meilleurs résultats sont obtenus avec les plus importants autels. (Autel pour les Sacrifices humains ou mieux, Autel Sacrificiel)</French>
		<Italian>I migliori risultati si ottengono con gli altari migliori (l'altare per i sacrifici umani oppure l'altare sacrificale). Si ottengono migliori risultati se in città sono presenti le tradizioni druidiche o le religioni mesoamericane, con i relativi edifici religiosi; perfino alcune meraviglie migliorano i risultati.</Italian>
		<Polish>Najlepsze rezultaty osi&#185;ga si&#234; z najlepszych O&#179;arzy (O&#179;tarzy Ofiar z ludzi lub z Ofiarnych O&#179;tarzy). Jeszcze lepsze rezultaty osi&#185;gaj&#185; wierz&#185;cy w Druidyzm lub mezo-ameryka&#241;ki Nagualizm (je&#156;li posiadaj&#185; Katedry i Klasztory tych religii). Niekt&#243;re Cudy Swiata maj&#185; tak&#191;e wp&#179;yw na zyski z Ofiar.</Polish>
		<Russian>Ëó÷øèå ðåçóëüòàòû ïðèõîäÿò ñ ëó÷øèìè æåðòâåííèêàìè (àëòàðü äëÿ ÷åëîâå÷åñêèõ æåðòâîïðèíîøåíèé èëè, ïðîùå ãîâîðÿ, Æåðòâåííèê). Ëó÷øèå ðåçóëüòàòû ïðîèñõîäÿò ñ Äðóèäèçìîì è Ìåçîàìåðèêàíñêèìè ðåëèãèÿìè è èõ ìîíàñòûðÿìè è ñîáîðàìè. Íåêîòîðûå ×óäåñà òàêæå ìîãóò óëó÷øèòü ðåçóëüòàò.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_SACRIFICE_CAPTIVE_MESSAGE</Tag>
		<English>Your people are pleased with the sacrifice.</English>
		<French>Votre peuple est satisfait du sacrifice.</French>
		<Italian>I tuoi sudditi sono felici del sacrificio.</Italian>
		<Polish>Twoi ludzie s&#185; zadowoleni z ofiary.</Polish>
		<Russian>Âàøè ëþäè îáðàäîâàíû æåðòâîïðèíîøåíèåì.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_OUTCOME_SACRIFICE_CAPTIVE_RELIGION</Tag>
		<English>The best results come with the best altars (Altar for Human Sacrifice or the better Sacrificial Alter). Some wonders also improve the outcome.</English>
		<French>Les meilleurs résultats sont obtenus avec les plus importants autels. (Autel pour les Sacrifices humains ou mieux, Autel Sacrificiel)</French>
		<Italian>I migliori risultati si ottengono con gli altari migliori (l'altare per i sacrifici umani oppure l'altare sacrificale). Si ottengono migliori risultati se in città sono presenti le tradizioni druidiche o le religioni mesoamericane, con i relativi edifici religiosi; perfino alcune meraviglie migliorano i risultati.</Italian>
		<Polish>Najlepsze rezultaty osi&#185;ga si&#234; z najlepszych O&#179;arzy (O&#179;tarzy Ofiar z ludzi lub z Ofiarnych O&#179;tarzy). Niekt&#243;re Cudy Swiata maj&#185; tak&#191;e wp&#179;yw na zyski z Ofiar.</Polish>
		<Russian>Ëó÷øèå ðåçóëüòàòû ïðèõîäÿò ñ ëó÷øèìè æåðòâåííèêàìè (àëòàðü äëÿ ÷åëîâå÷åñêèõ æåðòâîïðèíîøåíèé èëè, ïðîùå ãîâîðÿ, Æåðòâåííèê). Íåêîòîðûå ×óäåñà òàêæå ñïîñîáíû óëó÷øèòü ðåçóëüòàò.</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/Modules/zWIP/ExtraDiplomacy/ExtraDiplomacy_CIV4GameText_Outcomes.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_MISSION_DIPLOMAT_ASSIMULATE_IND_PEOPLE</Tag>
		<English>Assimulate Indigenous Peoples</English>
		<French>Assimiler ces Peuples Indigènes</French>
		<Italian>Assimila la comunità indigena</Italian>
		<Polish>Asimiluj Tubylc&#243;w</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_DIPLOMAT_PRAISE_IND_PEOPLE</Tag>
		<English>Assimulate Indigenous Peoples</English>
		<French>Assimiler ces Peuples Indigènes</French>
		<Italian>Celebra la comunità indigena</Italian>
		<Polish>Asimiluj Tubylc&#243;w</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_DIPLOMAT_SPEAK_TO_BARBARIAN_LEADERS</Tag>
		<English>Speak with barbarian leaders.</English>
		<French>Parler avec les chefs barbares.</French>
		<Italian>Parla con i leader barbarici.</Italian>
		<Polish>Porozmawiaj z przyw&#243;dcami barbarzy&#241;c&#243;w.</Polish>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_MISSION_DIPLOMAT_SPREAD_RELIGION</Tag>
		<English>Spread your State religion to barbarian city.</English>
		<French>Propager votre Religion d'Etat à la cité barbare.</French>
		<Italian>Diffondi la tua religione di stato nella città barbarica.</Italian>
		<Polish>Konwertuj barbarzy&#241;skie miasto do Twojej religii pa&#241;stwowej.</Polish>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Platyping_CIV4GameText.xml
<?xml version="1.0" encoding="UTF-8"?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_CONCEPT_WORLD_TECH</Tag>
		<English>1. World Tech</English>
		<French>1. Tech Mondiale limitée</French>
		<Italian>Tecnologia mondiale</Italian>
		<Russian>1. Уникальные технологии</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_CONCEPT_WORLD_TECH_PEDIA</Tag>
		<English>A World Tech is a technology that can be researched by a limited number of nations in the game. Once this set number of nations has researched the tech, no others can. Original code by Platyping.[PARAGRAPH:2]In Caveman2Cosmos the Religion techs are considered World Techs, as only one nation can research each of them. This is because those techs are both dead ends and one-shot techs and this was the only way to ensure the AI nations did not waste research on those already discovered.</English>
		<French>Une Tech Mondiale limitée est une technologie qui peut être recherchée par un nombre limité de nations dans le jeu. Une fois que ce nombre aura fait des recherches sur la technologie, aucun autre ne le pourra. Code original de Platyping.[PARAGRAPH:2]Dans Caveman2Cosmos, les techniciens de la religion sont des techniciens du monde qu'une seule nation peut rechercher. C'est parce que ces technologies sont à la fois des technologies sans issue et à un coup et que c'était la seule façon de s'assurer que les nations de l'IA ne gaspillent pas la recherche sur celles déjà découvertes.</French>
		<Italian>Una tecnologia mondiale è una tecnologia che può essere ricercata da un numero limitato di nazioni nel gioco. Una volta che quel numero ha ricercato la tecnologia, nessun altro può farlo. Codice originale di Platyping.[PARAGRAPH:2]In Caveman2Cosmos le tecnologie legate a una religione sono tecnologie mondiali che solo una nazione può ricercare.</Italian>
		<Russian>Уникальная технология - знание, которое может быть получено ограниченным числом цивилизаций. Как только одна из их числа исследует технологию, другим она будет уже не доступна.[PARAGRAPH:2]Наглядным примером являются религиозные технологии, которые может исследовать только одна цивилизация. Данные технологии являются тупиковыми и одноразовыми - это единственный способ гарантировать то, что компьютерные игроки не потратят впустую очки исследования на заведомо бесполезные цели.</Russian>
	</TEXT>
</Civ4GameText>
