=== Stones2Stars/Stones2Stars/Assets/XML/Schema/Civ4GameText.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.firaxis.com" elementFormDefault="qualified" targetNamespace="http://www.firaxis.com">
  <xs:element name="Civ4GameText">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TEXT" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element ref="Tag"/>
              <xs:element name="English" type="Gametext"/>
              <xs:element name="French" type="Gametext" minOccurs="0"/>
              <xs:element name="German" type="Gametext" minOccurs="0"/>
              <xs:element name="Italian" type="Gametext" minOccurs="0"/>
              <xs:element name="Spanish" type="Gametext" minOccurs="0"/>
              <xs:element name="Polish" type="Gametext" minOccurs="0"/>
              <xs:element name="Russian" type="Gametext" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tag">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="TXT_[\c-[:]]*|AI_DIPLO_[\c-[:]]*|USER_DIPLO_[\c-[:]]*|INTERFACE_[\c-[:]]*"/>
        <xs:whiteSpace value="collapse"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType mixed="true" name="Gametext">
    <xs:all>
      <xs:element name="Text" type="xs:string" minOccurs="0"/>
      <xs:element name="Gender" type="xs:NMTOKEN" minOccurs="0"/>
      <xs:element name="Plural" type="xs:NMTOKEN" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Modules/Alt_Timelines/Lara_Croft/LaraCroft_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_UNIT_LARA_CROFT</Tag>
		<English>Lara Croft</English>
		<French>
			<Text>Lara Croft</Text>
			<Gender>Female</Gender>
			<Plural>0</Plural>
		</French>
		<German>
			<Text>Lara Croft</Text>
			<Gender>Female</Gender>
			<Plural>0</Plural>
		</German>
		<Italian>Lara Croft</Italian>
		<Spanish>
			<Text>Lara Croft</Text>
			<Gender>Female</Gender>
			<Plural>0</Plural>
		</Spanish>
		<Russian>Лара Крофт</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_UNIT_LARA_CROFT_PEDIA</Tag>
		<English>The daughter of Lord Henshingly Croft, Lara was brought up in the sheltered world of aristocracy surrounded by tennis, butlers, and corgis. But this all started to change when she went to the renowned school of Gordonstoun and found the mountains of Scotland. Later, at her Swiss finishing school, she took to the art of extreme skiing and spent a holiday in the Himalayas searching for more challenging terrain. On her return trip however, the plane crashed deep within the mountains and Lara was the only survivor. Two weeks later, when she walked into a mountain village, her experiences had a profound effect on her. Unable to stand the suffocating atmosphere of upper-class British society any longer, she realized she was only truly alive when she was travelling alone. Despite this drastic life change, Lara still retains the essence of her upbringing - most notably with her polite, upper-class accent. Lara's parents though, having sported hopes of her marrying the Earl of Farringdon, were less than convinced about this chosen lifestyle and ceased to associate with their daughter - even terminating her monthly allowance. The Earl is still waiting. While in England, Lara lives in a mansion in Surrey which she inherited many years ago. At one time she saw little use in it but now realizes that, if nothing else, it is at least handy for storing all the artifacts she has acquired on her travels. She has also had a custom-built assault course constructed in the grounds for training purposes.</English>
		<German>Lara Croft, Tochter von Lord Henshingly Croft, war von Geburt an ein Kind der Aristokratie. Nachdem sie im Alter von 21 Jahren ihre Schulausbildung abgeschlossen hatte, schien eine Heirat mit einem wohlhabenden Mann schon sicher. Aber auf dem Rückweg von einem Skiausflug stürzte sie mit ihrem Charterflugzeug tief im Herzen des Himalaja Gebirges ab. Als einzige Überlebende lernte Lara, dass es von ihrer Intelligenz abhing, auf welche Weise sie in dieser feindlichen Umgebung, fernab von der schützenden Stätte ihrer Kindheit, überleben würde. Als sie 2 Wochen später im Dorf Tokakeriby eintraf, hatten die zurückliegenden Erfahrungen einen tiefen Eindruck auf sie hinterlassen. Unfähig, noch länger die enge und erstickende Atmosphäre der britischen Oberschicht zu ertragen, wurde sie sich darüber klar, dass sie nur dann wirklich leben würde, wenn sie sich alleine auf Reisen um die Welt begibt. In den nächsten 8 Jahren eignete sie sich ein umfangreiches Wissen über antike Zivilisationen der Erde an. Doch bald darauf schon verstieß die Familie ihre verschwenderische Tochter, so dass sie sich der Schriftstellerei zu wandte, um ihre Reisen zu finanzieren. Sie wurde nicht nur durch die Entdeckungen mehrerer, für die Archäologie äußerst interessanter antiker Stätten berühmt, sondern machte sich außerdem durch die Herausgabe von Reisetagebüchern und detaillierten Protokollen ihrer archäologischen Auswertungen einen Namen.</German>
		<Italian>Figlia di Lord Henshingly Croft, Lara fu cresciuta nel mondo sicuro dell'aristocrazia, circondata da tennis, maggiordomi e cortesie. Tutto ciò iniziò a cambiare quando lei andò alla rinomata scuola di Gordonstoun e scoprì le montagne della Scozia. In seguito, mentre era in una scuola svizzera, apprese l'arte dello sci estremo e trascorse una vacanza in Himalaya, alla ricerca di terreni più impegnativi. Durante il viaggio di ritorno però l'aereo precipitò sulle montagne, e Lara fu l'unica sopravvissuta. Due settimane dopo, quando entrò a piedi in un villaggio di montagna, le sue esperienze avevano avuto un profondo effetto su di lei. Incapace di sopportare l'opprimente atmosfera dell'alta società inglese, capì di essere veramente viva solo quando viaggiava da sola. Nonostante questo drastico cambio di vita, Lara mantiene l'essenza della propria educazione, in particolare il suo accento educato dell'alta società. I genitori di Lara però, avendo sperato che lei sposasse il Duca di Farringdon, non erano convinti di questo stile di vita e tagliarono i contatti con lei, sospendendo il suo vitalizio mensile. Il Duca sta ancora aspettando. Quando è in Inghilterra Lara vive in una villa nel Surrey, che ha ereditato molti anni fa. A un certo punto la riteneva poco utile, ma ora Lara capisce che è utile almeno per conservare tutti gli artefatti che ha recuperato nei suoi viaggi. Si è fatta anche costruire un percorso di guerra personalizzato nel giardino.</Italian>
		<Polish>C&#243;rka lorda Henshingly'ego Crofta. Wychowywana by&#179;a na arystokratk&#234;, zar&#234;czona by&#179;a z fikcyjnym hrabi&#185; Ferringdon. Ucz&#234;szcza&#179;a do szko&#179;y z internatem Gordonstoun w Szwajcarii, tam te&#191; ucz&#234;szcza&#179;a do finishing school. Po katastrofie samolotu w Himalajach samotnie sp&#234;dzi&#179;a dwa tygodnie w g&#243;rach. Wydarzenia te sprawi&#179;y, &#191;e porzuci&#179;a swoje dawne &#191;ycie, a zacz&#234;&#179;a wie&#156;&#230; &#191;ywot podr&#243;&#191;uj&#185;cej po &#156;wiecie poszukiwaczki przyg&#243;d. Na podstawie swoich przyg&#243;d jako najemniczka, my&#156;liwy i mistrzyni z&#179;odziejstwa napisa&#179;a ksi&#185;&#191;ki i inne publikacje. Na potrzeby p&#243;&#159;niejszych gier historia zosta&#179;a zmieniona - w samolocie znajdowa&#179;a si&#234; r&#243;wnie&#191; jej matka. Podczas poszukiwania schronienia Croft by&#179;a &#156;wiadkiem znikni&#234;cia matki, kt&#243;ra dotkn&#234;&#179;a staro&#191;ytnego miecza. Lord Croft zagin&#185;&#179;, poszukuj&#185;c &#191;ony.</Polish>
		<Russian>Дочь лорда Хеншингли Крофта появилась на свет в аристократическом мире, окруженная слугами, общественными событиями и высшим обществом. Но все это начало меняться, когда она попала в Горлонстаунскую школу и открыла для себя горы Шотландии. Позднее, в Швейцарской высшей школе она стала заниматься экстремальной ездой на лыжах, а потом провела выходные в Гималаях, пробуя более сложную местность. Однако, когда она летела назад, самолет разбился где-то в горах и Лара оказалась единственной выжившей. Через две недели она добралась до маленькой деревни в горах. Но опыт этого происшествия оказал на нее решающее влияние. Больше не в силах выносить замкнутую атмосферу высшего британского общества, Лара поняла, что по-настоящему она живет, только когда путешествует в одиночку. Семья Лары, возлагавшая большие надежды на ее женитьбу с Эрлом Фаррингдоном, была более чем возмущена этой переменой и отказалась от всяческих связей с ней. Лара живет в Англии, в своем особняке в Суррее, который унаследовала много лет назад. Поначалу она не видела в нем большой пользы, но потом поняла, что, по крайней мере, в нем можно хранить свои трофеи. На территории особняка у нее имеется построенная по заказу тренировочная полоса препятствий.</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Tools/Autocorrect/AutocorrectTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Sid Meier's Civilization 4 Beyond the Sword -->
<!-- Modified by the World of Civilization Team -->
<!-- Game Text Infos -->
<!-- -->
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BONUS_CRYSTAL_GLASSWARE</Tag>
		<English>Crystal Glassware</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_CRYSTAL_GLASSWARE_PEDIA</Tag>
		<English>Lead glass is a variety of glass in which lead replaces the calcium content of a typical potash glass. Lead glass contains typically 18-40 weight% lead(II) oxide (PbO), while modern [BOLD]lead crystal[\BOLD], historically also known as flint glass due to the original silica source, contains a minimum of 24% PbO. Lead glass is desirable owing to its decorative properties.[PARAGRAPH:2]Discovered by Englishman George Ravenscroft in 1674, the technique of adding lead oxide (in quantities of between 10 and 30%) improved the appearance of the glass and made it easier to melt using sea-coal as a furnace fuel. This technique also increased "working period" making the glass easier to manipulate.[PARAGRAPH:2]The term lead crystal is, by technicality, not an accurate term to describe lead glass, as glass, an amorphous solid, lacks a crystalline structure. The use of the term lead crystal remains popular for historical and commercial reasons. It is retained from the Venetian word cristallo to describe the rock crystal imitated by Murano glassmakers. This naming convention has been maintained to the present day to describe decorative hollow-ware.[PARAGRAPH:2]Lead crystal glassware was formerly used to store and serve drinks, but due to the potential health risks of lead, this is rare nowadays. One alternative material is [BOLD]crystal glass[\BOLD], in which barium oxide, zinc oxide, or potassium oxide are employed instead of lead oxide. Lead-free crystal has a similar refractive index to lead crystal, but it is lighter and it has less dispersive power.[PARAGRAPH:2]Source: Wikipedia.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_FAKE_GEMS</Tag>
		<English>Fake Gems</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_FAKE_GEMS_PEDIA</Tag>
		<English>Faience beads were common in the ancient world, being similar to glaze they were made by grinding quartz, mixing it with a colouring agent and firing. The Harappan craftsmen made fake Turquoise and Lapis beads that were considered better than the natural stone because they did not tarnish.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_MING_VASE</Tag>
		<English>Ming Vase</English>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/Modules/zWIP/Antiquities (broken)/Antiquities_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../../Xml/Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_CAVE</Tag>
		<English>Antiquities - Grave Goods (Cave)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_EARTH</Tag>
		<English>Antiquities - Grave Goods (Earth)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_FIRE</Tag>
		<English>Antiquities - Grave Goods (Fire)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_ANTIQUITIES_GRAVE_GOODS_SKY</Tag>
		<English>Antiquities - Grave Goods (Sky)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BONUS_BURIAL_GOODS_PEDIA</Tag>
		<English>Grave Goods made in ancient times and traded as antiquities to the rich and Museums.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_CAVE</Tag>
		<English>Grave Goods (Cave)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_EARTH</Tag>
		<English>Grave Goods (Earth)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_FIRE</Tag>
		<English>Grave Goods (Fire)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_PEDIA</Tag>
		<English>Game auto builds used to provide antiquities at Archaeology.</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_BURIAL_GOODS_SKY</Tag>
		<English>Grave Goods (Sky)</English>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_GRAVE_GOODS</Tag>
		<English>Grave Goods</English>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Traditions_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_BUILDING_TRADITION_ARCHERY</Tag>
		<English>Tradition - Archery</English>
		<French>Tradition - Archerie</French>
		<German>Tradition - Bogenschießen</German>
		<Italian>Tradizione del tiro con l'arco</Italian>
		<Russian>Традиция - Лучники</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EFFECT_TRADITION_ARCHERY</Tag>
		<English>Effect - Tradition - Archery</English>
		<French>Effect (Tradition - Archerie)</French>
		<German>Effekt (Tradition - Bogenschießen)</German>
		<Italian>Effetto della tradizione del tiro con l'arco</Italian>
		<Russian>Эффект - Традиция - Лучники</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EFFECT_TRADITION_ARCHERY_PEDIA</Tag>
		<English>Archers are improved.</English>
		<French>Les Archers sont améliorés.</French>
		<German>Bogenschützen sind verbessert.</German>
		<Italian>Le unità arciere sono state migliorate.</Italian>
		<Russian>Лучники улучшены.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_TRADITION_ARCHERY_PEDIA</Tag>
		<English>Archery is encouraged in your nation.</English>
		<French>L'Archerie est encouragée dans votre nation.</French>
		<German>Bogenschießen wird im Land gefördert.</German>
		<Italian>Il tiro con l'arco è incoraggiato nella tua nazione.</Italian>
		<Russian>Стрельба из лука поощряется в вашей стране.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_TRADITION_AESTHETIC_APPRECIATION</Tag>
		<English>Tradition - Aesthetic Appreciation</English>
		<French>Tradition (Appréciation esthétique)</French>
		<German>Tradition - Ästhetische Würdigung</German>
		<Italian>Tradizione dell'apprezzamento estetico</Italian>
		<Russian>Традиция - Эстетическая Оценка</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EFFECT_TRADITION_AESTHETIC_APPRECIATION</Tag>
		<English>Effect - Tradition - Aesthetic Appreciation</English>
		<French>Effet - Tradition (Appréciation esthétique)</French>
		<German>Effekt - Tradition - Ästhetische Würdigung</German>
		<Italian>Effetto della tradizione sull'apprezzamento estetico</Italian>
		<Russian>Эффект - Традиция - Эстетическая Оценка</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_TRADITION_AESTHETIC_APPRECIATION_PEDIA</Tag>
		<English>Aesthetic appreciation is commonly referred to as the appreciation of beauty and excellence, defined by Peterson and Seligman as the ability to find, recognize, and take pleasure in goodness in the physical and social worlds.</English>
		<French>L'appréciation esthétique est communément désignée comme l'appréciation de la beauté et de l'excellence, définie par Peterson et Seligman comme la capacité à trouver, reconnaître et prendre plaisir à la bonté dans les mondes physique et social.</French>
		<German>Ästhetische Würdigung ist die allgemeine Wertschätzung von Schönheit und Perfektion. Peterson und Seligman definieren sie als Fähigkeit, Ästhetik zu finden, zu erkennen und sich an ihr zu erfreuen, sowohl im physischen wie im sozialen Umfeld.</German>
		<Italian>L'apprezzamento estetico è comunemente indicato come l'apprezzamento della bellezza e dell'eccellenza, definito da Peterson e Seligman come la capacità di trovare, riconoscere e trarre piacere dalla bellezza nel mondo fisico e sociale.</Italian>
		<Russian>Эстетическая оценка обычно называется оценкой красоты и совершенства, определяемой Петерсоном и Селигманом как способность находить, распознавать и получать удовольствие от добра в физическом и социальном мирах.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_TRADITION_WORK_ETHIC</Tag>
		<English>Tradition - Work Ethic</English>
		<French>Tradition - Éthique du Travail</French>
		<German>Tradition - Arbeitsmoral</German>
		<Italian>Tradizione dell'etica del lavoro</Italian>
		<Russian>Традиция - Трудовая Этика</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_EFFECT_TRADITION_WORK_ETHIC</Tag>
		<English>Effect - Tradition - Work Ethic</English>
		<French>Effet (Tradition - Éthique du Travail)</French>
		<German>Effekt - Tradition - Arbeitsmoral</German>
		<Italian>Effetto della tradizione dell'etica del lavoro</Italian>
		<Russian>Эффект - Традиция - Трудовая Этика</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_BUILDING_TRADITION_WORK_ETHIC_PEDIA</Tag>
		<English>Work ethic is a value based on hard work and diligence.</English>
		<French>L'Éthique du travail est une valeur basée sur la diligence et le labeur.</French>
		<German>Arbeitsmoral basiert auf Fleiß und harter Arbeit.</German>
		<Italian>L'etica del lavoro è un valore basato sul duro lavoro e sulla diligenza.</Italian>
		<Russian>Трудовая этика - ценность, основанная на тяжелом труде и прилежании.</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_PROMOTION_ARCHER_TRADITION</Tag>
		<English>Archer Tradition</English>
		<French>Tradition des Archers</French>
		<German>Tradition des Bogenschießens</German>
		<Italian>Tiro con l'arco tradizionale</Italian>
		<Russian>Опытный лучник</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_PROMOTION_TRADITION_ASTHETIC_APPRECIATION</Tag>
		<English>Aesthetic Appreciation</English>
		<French>Appréciation esthétique</French>
		<German>Ästhetische Würdigung</German>
		<Italian>Apprezzamento estetico</Italian>
		<Russian>Эстетическая Оценка</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_PROMOTION_TRADITION_WORK_ETHIC</Tag>
		<English>Work Ethic</English>
		<French>Éthique du Travail</French>
		<German>Arbeitsmoral</German>
		<Italian>Etica del lavoro</Italian>
		<Russian>Трудовая Этика</Russian>
	</TEXT>
</Civ4GameText>

=== Stones2Stars/Stones2Stars/Assets/XML/GameText/Special/_LanguageIndex_CIV4GameText.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- Composite texts: Those TXT keys are enumerated by DLL and Python. Used to select language. -->
<Civ4GameText xmlns="http://www.firaxis.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.firaxis.com ../../Schema/Civ4Gametext.xsd">
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_0</Tag>
		<English>English</English>
		<French>Anglais</French>
		<German>English</German>
		<Italian>Inglese</Italian>
		<Spanish>Inglés</Spanish>
		<Polish>Angielski</Polish>
		<Russian>Английский</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_1</Tag>
		<English>French</English>
		<French>Français</French>
		<German>Français</German>
		<Italian>Francese</Italian>
		<Spanish>Francés</Spanish>
		<Polish>Francuski</Polish>
		<Russian>Французкий</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_2</Tag>
		<English>German</English>
		<French>Allemand</French>
		<German>Deutsch</German>
		<Italian>Tedesco</Italian>
		<Spanish>Alemán</Spanish>
		<Polish>Niemiecki</Polish>
		<Russian>Немецкий</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_3</Tag>
		<English>Italian</English>
		<French>Italien</French>
		<German>Italiano</German>
		<Italian>Italiano</Italian>
		<Spanish>Italiano</Spanish>
		<Polish>W&#179;oski</Polish>
		<Russian>Итальянский</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_4</Tag>
		<English>Spanish</English>
		<French>Espagnol</French>
		<German>Español</German>
		<Italian>Spagnolo</Italian>
		<Spanish>Español</Spanish>
		<Polish>Hiszpa&#241;ski</Polish>
		<Russian>Испанский</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_5</Tag>
		<English>Polish</English>
		<French>Polonais</French>
		<German>Polnisch</German>
		<Italian>Polacco</Italian>
		<Spanish>Polaco</Spanish>
		<Polish>Polski</Polish>
		<Russian>Польский</Russian>
	</TEXT>
	<TEXT>
		<Tag>TXT_KEY_LANGUAGE_6</Tag>
		<English>Russian</English>
		<French>Russe</French>
		<German>Russisch</German>
		<Italian>Russo</Italian>
		<Spanish>Ruso</Spanish>
		<Polish>Rosyjski</Polish>
		<Russian>Русский</Russian>
	</TEXT>
</Civ4GameText>
